# See user manual at https://www.ufactory.cc/wp-content/uploads/2023/07/UFactory-850-User-Manual-V2.1.0.pdf
#
_target_: lerobot.common.robot_devices.robots.manipulator.ManipulatorRobot
robot_type: u850
calibration_dir: .cache/calibration/u850

# `max_relative_target` limits the magnitude of the relative positional target vector for safety purposes.
# Set this to a positive scalar to have the same value for all motors, or a list that is the same length as
# the number of motors in your follower arms.
max_relative_target: null

leader_arms:  # L
  left:
    _target_: lerobot.common.robot_devices.motors.gello.GelloDynamixelWrapper
    port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT9BTDLW-if00-port0"
    motors:
      # name: (index, model)
      joint1: [1, "xl330-m288"]
      joint2: [2, "xl330-m288"]
      joint3: [3, "xl330-m288"]
      joint4: [4, "xl330-m288"]
      joint5: [5, "xl330-m288"]
      joint6: [6, "xl330-m288"]
      gripper: [7, "xl330-m077"]
  right:
    _target_: lerobot.common.robot_devices.motors.gello.GelloDynamixelWrapper
    port: "/dev/serial/by-id/usb-FTDI_USB__-__Serial_Converter_FT9BTEGF-if00-port0"
    motors:
      # name: (index, model)
      joint1: [1, "xl330-m288"]
      joint2: [2, "xl330-m288"]
      joint3: [3, "xl330-m288"]
      joint4: [4, "xl330-m288"]
      joint5: [5, "xl330-m288"]
      joint6: [6, "xl330-m288"]
      gripper: [7, "xl330-m077"]

follower_arms:
  left:
    _target_: lerobot.common.robot_devices.motors.ufactory.XArmWrapper
    port: 192.168.1.236
    motors:
      # name: (index, model)
      joint1: [1, "ufactory-850"]  # +/- 360 degrees
      joint2: [2, "ufactory-850"]  # +/- 132 degrees
      joint3: [3, "ufactory-850"]  # -242 to 3.5 degrees
      joint4: [4, "ufactory-850"]  # +/- 360 degrees
      joint5: [5, "ufactory-850"]  # +/- 124 degrees
      joint6: [6, "ufactory-850"]  # +/- 360 degrees
      # joint7: [7, "ufactory-850"]  # NOT PRESENT in 850
      gripper: [7, "ufactory-850"]  # gripper
    enable_filtering: true
    smoothing_factor: 0.1
    gripper_update_interval: 0.1  # Update gripper every 100ms

  right:
    _target_: lerobot.common.robot_devices.motors.ufactory.XArmWrapper
    port: 192.168.1.218
    motors:
      # name: (index, model)
      joint1: [1, "ufactory-850"]  # +/- 360 degrees
      joint2: [2, "ufactory-850"]  # +/- 132 degrees
      joint3: [3, "ufactory-850"]  # -242 to 3.5 degrees
      joint4: [4, "ufactory-850"]  # +/- 360 degrees
      joint5: [5, "ufactory-850"]  # +/- 124 degrees
      joint6: [6, "ufactory-850"]  # +/- 360 degrees
      # joint7: [7, "ufactory-850"]  # NOT PRESENT in 850
      gripper: [7, "ufactory-850"]  # gripper
    enable_filtering: true
    smoothing_factor: 0.1
    gripper_update_interval: 0.1  # Update gripper every 100ms

cameras:
  top:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 10
    fps: 30
    width: 640
    height: 480
  wrist_left:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 4
    fps: 30
    width: 640
    height: 480
  wrist_right:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: 16
    fps: 30
    width: 640
    height: 480
